version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: yemen_db
    restart: always
    environment:
      - POSTGRES_DB=yemen_market
      - POSTGRES_USER=yemen_user
      - POSTGRES_PASSWORD=yemen_pass
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: yemen_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data_new:
